use frame;
CREATE TABLE chat_blackid (
  id int(11) NOT NULL AUTO_INCREMENT,
  guid int(11) NOT NULL,
  end_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8